### ISSUE TITLE
translation in Korean

### ISSUE THREAD

**Issue by Leeyuryeon** [luyadev/luya-module-styleguide#5]
Hello, my name is Lee yuryeon. I would like to translate the README and LICENSE documents into Korean. Can I translate?

**Comment by nadar** [comment]
Hi @Leeyuryeon only for the styleguide module or LUYA in general?

**Comment by nadar** [comment]
Because in order to run this styleguide module you need a full LUYA (https://luya.io) installation

**Comment by Leeyuryeon** [comment]
Sorry, but the comments above are not exactly understandable. I just want to translate the README and LICENSE documents into English and link them. I have not used github in a while. Thank you for your understanding.

**Comment by TheMaaarc** [comment]
Hi @Leeyuryeon - If you want to translate the Readme of [luya-module-styleguide](https://github.com/luyadev/luya-module-styleguide) to Korean I would suggest you start with [luya](https://github.com/luyadev/luya) because [luya-module-styleguide](https://github.com/luyadev/luya-module-styleguide) depends on [luya](https://github.com/luyadev/luya) and it doesn't help anyone if you have a MODULE that depends on LUYA which is not translated.

See here: https://github.com/luyadev/luya/issues/1159

**Comment by Leeyuryeon** [comment]
Good advice, thank you! I'll try it soon!!
